version: '3.2'
services:
  api1:
      build: ./
      tty: true
  api2:
      build: ./
      tty: true
  api3:
      build: ./
      tty: true
  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - api1
          - api2
          - api3
      ports:
          - '1234:1234'
  static:
      build: ./client
      tty: true
      ports:
          - '80:80'